apiVersion: v1
kind: Service
metadata:
  name: quarkusfingerpaint
  labels:
    app: quarkusfingerpaint    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: quarkusfingerpaint
  type: LoadBalancer